---
title: "Tidycensus Walkthrough"
author: "Jackson M Luckey"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Messy Start

I used the R package Tidycensus to download census data. Tidycensus was created by Kyle Walker and is maintained by a community on GitHub. Tidycensus allows "R users to return Census and ACS data as tidyverse-ready data frames, and optionally returns a list-column with feature geometry for many geographies". The "list-column with feature geometry" allows the R user to easily draw maps using the downloaded census data and ggplot2. Dataframes can be downloaded in either a wide or tidy format, and brief descriptions of each variable are available. The package is an API wrapper for data.census.gov, and the API calls it creates can be accessed and manually ran using packages such as rvest. The package supports both American Community Survey and Decennial data. To pull down data with Tidycensus, you need to know the variable/table name, the year, the geographic level, and the survey.

 To identify the variables and tables available from a survey, I used the command `tidycensus::load_variables(year, survey)`, where year is a year in numerical format (e.g. 2018), and survey is a survey in character format (e.g. "acs1"). To search for variables within a specific table in the survey, filter the output of `load_variables()` with `filter(stringr::str_detect(name, pattern))`, where pattern is the table name followed by an underscore. This was abstracted away as Variable names can be merged with the tidy output of another Tidycensus call by using `rename(variable = name)` to change the column names of the output of `load_variables()` to match the column names of a Tidycensus dataframe, and then using `dplyr::left_join(tidycensus_dataframe, output_of_load_variables, by = c("name" = "name"))`.
 
The geographical level, survey, and year are all easier to determine. Geographical levels are things like state, county, school district, census tract, and congressional district. They are represented as characters. Not all geographical levels are supported by Tidycensus, and not all surveys are available for all geographies. Surveys include the different American Community Surveys, the Decennial census, and supplemental estimates. They can be found on the U.S. Census's website. Finally, year is simply a valid year for that survey provided as a number.

To pull down actual data from census.data.gov using Tidycensus, you use one of three functions depending on the survey that you are working with. To work with the decennial census, use `get_decennial()`. To work with American Community Survey data, use `get_acs()`. Finally, use `get_estimates()` to work with the Census Bureau's population estimates API. If you download the data in wide format, Tidycensus returns a table with the columns `GEOID` and `NAME`, which refer to the geographical region, and two columns, `Table_Variable + E` and `Table_Variable + M`, for each variable in the table. For example, if the table was "someTable", and it only included the variables "001" and "002", the returned dataframe would included the columns `someTable_001E, someTable_001M, someTable_002E, someTable_002M`. E refers to estimate, while M refers to margin of error. Finally, if you included the argument `geometry = TRUE` in the call, there will be a column `geometry` that includes the data required to draw a map of the geographical regions included in the call.

In order to better use Tidycensus, I wrote custom functions to accomplish several repeated tasks. One function, `get_census_tables_multiple_years(table, years)`, allows the user to download multiple years of a particular census table at once. The functions accept a table code and year range, and downloads the table for each year, pivot it into a wide format, adds a year column, and binds the rows of the resulting dataframes into one master dataframe, which is returned. Another function, `clean_county_col(df)`, modifies the "county" column, removing the string "County, Ohio" from each entry in order to make it easier to join with other datasets.

Census tables were identified through several means. Using Tidycensus's "load_variables" function, I created a dataframe of all variables covered in the package and filtered it using keywords and R's grep wrapper. Keywords were selected by brainstorming off of the hypothesis that the literature put forward. For example, I used the keyword "disability" for the disability variables, "median income" and "average income" and "mean income" for income, and so on.